### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by PavlosMelissinos** [lizi-git/Social-Network-Embedding#1]
Hello!

Running the example throws the following error:

```
Traceback (most recent call last):
  File "SNE_runner.py", line 5, in <module>
    from SNE import SNE
  File "~/Desktop/Graph_embedding/projects/Social-Network-Embedding/SNE.py", line 13, in <module>
    import evaluation
ImportError: No module named evaluation
```

Which module does evaluation refer to? [SNE.py#L13](https://github.com/lizi-git/Social-Network-Embedding/blob/master/SNE.py#L13)

Thanks!

**Comment by liziliao** [comment]
I have updated it. The code is included.

**Comment by PavlosMelissinos** [comment]
Thanks. :)
