### ISSUE TITLE
I don't understand what's wrong with 'async' in pywrap_tensorflow_internal.py. It reports error 'invalid syntax'.

### ISSUE THREAD

**Issue by Caesarsar** [lizi-git/Social-Network-Embedding#10]
Here is the error：
-----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/InstallationPackage/ASNE-master/SNE_runner.py", line 5, in <module>
    from SNE import SNE
  File "D:\InstallationPackage\ASNE-master\SNE.py", line 11, in <module>
    import tensorflow as tf
  File "C:\Users\Drenched\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Drenched\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Drenched\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Drenched\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 114
    def TFE_ContextOptionsSetAsync(arg1, async):
                                             ^
SyntaxError: invalid syntax
---------------------------------------------------------------------------------------------------
I would appreciate it if someone can help me.

**Comment by Caesarsar** [comment]
My tensorflow version is 1.10.0, I can't collect 0.12.1 and it reports 
'ERROR: Could not find a version that satisfies the requirement 0.12.1 (from versions: none)
ERROR: No matching distribution found for 0.12.1' . :(

**Comment by Caesarsar** [comment]
Well I get it, tensorflow 0.12.1 was released for Python 3.6 but only on Linux and MacOS but mine is 3.7 hhha

**Comment by Caesarsar** [comment]
Well I get it, tensorflow 0.12.1 was released for Python 3.6 but only on Linux and MacOS but mine is 3.7 and windows hahahah
