### ISSUE TITLE
which tensorflow version should be?

### ISSUE THREAD

**Issue by SeekPoint** [lizi-git/Social-Network-Embedding#5]

**Comment by SeekPoint** [comment]
mldl@ub1604:~/ub16_prj/ASNE$ python SNE_runner.py --data_path data/ --id_dim 20 --attr_dim 20 --n_neg_samples 10 --epoch 20
('data_path: ', 'data/')
('attr_M:', 2788)
('id_N:', 18163)
('test link number:', 766800)
('Total training links: ', 766800)
('Total epoch: ', 20)
('id_dim :', 20)
('attr_dim :', 20)
Traceback (most recent call last):
  File "SNE_runner.py", line 45, in <module>
    run_SNE( Data, args.id_dim, args.attr_dim)
  File "SNE_runner.py", line 30, in run_SNE
    model = SNE( data, id_embedding_size=id_dim, attr_embedding_size=attr_dim)
  File "/home/mldl/ub16_prj/ASNE/SNE.py", line 33, in __init__
    self._init_graph()
  File "/home/mldl/ub16_prj/ASNE/SNE.py", line 57, in _init_graph
    self.embed_layer = tf.concat(1, [self.id_embed, self.alpha * self.attr_embed]) # batch_size * (id_dim + attr_dim)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1096, in concat
    dtype=dtypes.int32).get_shape().assert_is_compatible_with(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 836, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 926, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 383, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 303, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
mldl@ub1604:~/ub16_prj/ASNE$

**Comment by liziliao** [comment]
hi, the version should be 0.12.1

**Comment by AliceLee1203** [comment]
@loveJasmine  Did you run this package successfully? I face several issues that I can't run it successfully:(

**Comment by SeekPoint** [comment]
it works with tf0.12.1

**Comment by AliceLee1203** [comment]
@loveJasmine  let me check with it, maybe that's why I can't work successfully, thank you :)
